In [ ]:
numerical python
NumPy (Numerical Python) is a  Python library used for 
data analysis, and numerical operations. It provides fast and efficient tools for working 
with large datasets, especially arrays and matrices.

In [ ]:
num    py

In [ ]:
What is NumPy?

NumPy (Numerical Python) is a library used for:

Fast mathematical operations
Working with arrays (like lists but much more powerful)
🔹 Why use NumPy?

👉 Faster than Python lists
👉 Supports vector operations (no loops needed)
👉 Used in Pandas, ML, Data Science

In [ ]:
# vectorizrd operation

In [2]:
import numpy as np

In [1]:
# in python 
a = [1, 2, 3]   # *3
result = []

for x in a:
    result.append(x * 3)

print(result)

[3, 6, 9]


In [ ]:
set([1,2,3])

In [5]:
#Multiply every element by 3
a = np.array([1, 2, 3])

a * 3
# [3 6 9]

array([3, 6, 9])

In [6]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a = a * 2
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [2]:
# in python
A = [[1, 2, 3],
     [4, 5, 6]]

for i in range(len(A)):
    for j in range(len(A[i])):
        A[i][j] = A[i][j] * 2

print(A)

[[2, 4, 6], [8, 10, 12]]


In [ ]:
a ** 2

# boolean indexing

In [8]:
#NumPy expands b automatically to match A.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A[A>3]
# element-wise comparison

array([4, 5, 6])

In [22]:
# in python 
A = [[1, 2, 3],
     [4, 5, 6]]

result = []
for row in A:
    new_row = []
    for x in row:
        new_row.append(x > 3)
    result.append(new_row)

print(result)

[[False, False, False], [True, True, True]]


# numpy Important Attributes/Methods

In [9]:
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)
print(a)

2
[[1 2 3]
 [4 5 6]]


In [12]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [13]:
np.arange(1, 10, 2)   # start, stop, step

array([1, 3, 5, 7, 9])

In [15]:
#Array Attributes
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)   # (rows, cols)
print(arr.ndim)    # number of dimensions
print(arr.size)    # total elements

(2, 3)
2
6


In [25]:
#shape — tuple showing rows & columns
a.shape     # (2, 3)

(2, 3)

In [26]:
#size — total number of elements
a.size      # 6

6

In [27]:
#dtype — data type of elements
a.dtype    

dtype('int64')

In [ ]:
64-bit OS (most laptops/desktops) → int64

32-bit OS → int32
Type	Bytes per value
int32	4 bytes
int64	8 bytes

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#T — transpose (attribute)
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
#astype--- to convert the datatype
a.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# array creation method

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Range-based

In [23]:
for i in range(1,10,2):          # in list
    print(i)

1
3
5
7
9


In [11]:
arr=np.arange(1, 10, 2)
print(arr)
arr*2

[1 3 5 7 9]


array([ 2,  6, 10, 14, 18])

# Array Manipulation Methods

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#Reshaping
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Flattening

In [51]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

# statistics


In [2]:
import numpy as np

In [21]:
l=[10,20,30]
np.mean(l)

np.float64(20.0)

In [23]:
data = np.array([10, 20, 30, 40, 50])
np.mean(data)

np.float64(30.0)

In [31]:
np.median(data)

np.float64(30.0)

In [24]:
np.min(data)   # or data.min()
np.max(data)   # or data.max()

np.int64(50)

In [ ]:
np.sum(data)   # 150
np.prod(data)  # 12000000

# Broadcasting

In [ ]:
Broadcasting
Allows operations on arrays of different shapes.
NumPy automatically expands the smaller array along missing dimensions

In [25]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

arr2 = np.array([10,20,30])

print(arr1 + arr2)

[[11 22 33]
 [14 25 36]]


In [27]:
#Array–Array Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)        # [5, 7, 9]
x * y        # [4, 10, 18]
x-y
x>3
x*2

[5 7 9]


array([2, 4, 6])

# Concatenation
# Joining arrays together.

In [75]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [73]:
# 1D concatenation
c = np.concatenate([a, b])
print(c)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]


# indexing,slicing,iteration

In [2]:
a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [ ]:
a[0]     # 10
a[-1]    # 40

np.int64(40)

In [30]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A[0, 0]  # 1  (row 0, col 0)

np.int64(1)

In [5]:
A[1,2]  # 6  (row 1, col 2)

np.int64(6)

In [29]:
A[2,1] # 8  

np.int64(8)

In [9]:
a

array([10, 20, 30, 40])

In [10]:
# slicing 
A[1:3]   # [20, 30]

array([[4, 5, 6],
       [7, 8, 9]])

In [12]:
A[:3]  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
A[::2]   

array([[1, 2, 3],
       [7, 8, 9]])

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
#A[r1:r2 , c1:c2]
A[1:2, 0:1]

array([[4]])

In [34]:
A[0:2, 0:1]   # row 0

array([[1],
       [4]])

In [ ]:
A[:, 1]   # column 1
A[1:, :]  # all rows except first
A[:,2]    #all row,2 col
A[:2]      #0,1 row
A[:,1:3]  #all row,1,2 col
A[2:4,1:3] # 4 SKIP,3 skip 

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A[0,2]

np.int64(3)

# Fancy Indexing



In [33]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Pick rows 0 and 2:
A[[0, 2]]
# [[1, 2, 3],
#  [7, 8, 9]]

array([[1, 2, 3],
       [7, 8, 9]])

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

# numpy function

In [ ]:
Random Number Functions (np.random)
Function	Purpose	Example
np.random.rand()	Uniform [0,1)	np.random.rand(3,2) Values are never negative
np.random.randn()	Standard normal	np.random.randn(3,2) Standard Normal distribution  Mean (μ) = 0,Standard deviation (σ) = 1
np.random.randint()	Random integers	np.random.randint(0,10,5)
np.random.choice()	Random selection	np.random.choice([1,2,3],3)
np.random.seed()	Fix random seed	np.random.seed(42)

In [35]:
np.random.rand(3,3)         #0-1

array([[0.14226736, 0.11088517, 0.8967838 ],
       [0.39583566, 0.53551049, 0.16254985],
       [0.6849512 , 0.13026548, 0.21600369]])

In [28]:
np.random.randn(3,2)   #Values can be negative or positiv ,There is no fixed range ❌,Most values fall between -3 and +3,-2 and +2

array([[-0.8380058 , -1.64889052],
       [-1.06569608,  0.48716436],
       [ 0.54967523, -1.59592301]])

In [37]:
np.random.randint(0,100,5)

array([66, 77, 64, 71, 23], dtype=int32)

In [41]:
np.random.choice([1,2,3,4,5,6],3)

array([4, 1, 4])

In [44]:

np.random.seed(1)
np.random.randint(0,100,5)

array([37, 12, 72,  9, 75], dtype=int32)


# sorted  return python list 


In [30]:
a = np.random.randint(1, 100, 15)
print(a)
np.sort(a)#Returns a sorted copy of a (does not modify a in-place).
#sorted_list = np.sort(a).tolist()

[10 74 69  3 53 94 11 38  3 97 82 76 13 93 85]


array([ 3,  3, 10, 11, 13, 38, 53, 69, 74, 76, 82, 85, 93, 94, 97],
      dtype=int32)

# With Tuple

In [45]:


t = (1, 2, 3)
a = np.array(t)
print(a)

[1 2 3]


In [ ]:
# With Set

In [46]:
s = {1, 2, 3}
a = np.array(s)
print(a)

{1, 2, 3}


In [ ]:
#If using a set, convert to list
np.array(list(s))

# THANKS