In [ ]:
numerical python
NumPy (Numerical Python) is a  Python library used for 
data analysis, and numerical operations. It provides fast and efficient tools for working 
with large datasets, especially arrays and matrices.

In [ ]:
num    py

In [ ]:
1. Fast Computation

NumPy uses C languade in backend, making operations
much faster than pure Python lists.
NumPy provides built-in functions for:

Linear algebra

Statistics

Random number generation

Vectorized operations (no slow Python loops!)


Foundation for Many Libraries

Libraries like Pandas, SciPy, scikit-learn, TensorFlow, and PyTorch depend heavily on NumPy.

In [ ]:
Vectorized operations in NumPy mean performing operations on entire arrays at once, 
without writing explicit Python loops.

In [ ]:
# vectorizrd operation

In [1]:
import numpy as np

In [ ]:
# in python 
a = [1, 2, 3]   # *3
result = []

for x in a:
    result.append(x * 3)

print(result)

In [8]:
#Multiply every element by 3
a = np.array([1, 2, 3])
print(a)
a * 3
# [3 6 9]

[1 2 3]


array([3, 6, 9])

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a = a * 2
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [2]:
# in python
A = [[1, 2, 3],
     [4, 5, 6]]

for i in range(len(A)):
    for j in range(len(A[i])):
        A[i][j] = A[i][j] * 2

print(A)

[[2, 4, 6], [8, 10, 12]]


In [ ]:
a ** 2

In [1]:
import numpy as np

In [4]:
#with broadcasting
#NumPy expands b automatically to match A.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

A + b

array([[11, 22, 33],
       [14, 25, 36]])

In [3]:
# in python 
result = []
for row in A:
    new_row = []
    for i in range(len(b)):
        new_row.append(row[i] + b[i])
    result.append(new_row)

print(result)

[[np.int64(11), np.int64(22), np.int64(33)], [np.int64(14), np.int64(25), np.int64(36)]]


# boolean indexing

In [6]:
#NumPy expands b automatically to match A.
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A[A > 3]
# element-wise comparison

array([4, 5, 6])

In [22]:
# in python 
A = [[1, 2, 3],
     [4, 5, 6]]

result = []
for row in A:
    new_row = []
    for x in row:
        new_row.append(x > 3)
    result.append(new_row)

print(result)

[[False, False, False], [True, True, True]]


# numpy Important Attributes/Methods

In [ ]:
Summary Table
Category	                    Important Attributes/Methods

Attributes               	    ndim, shape, size, dtype, itemsize, nbytes, T
Creation	                     array, zeros, ones, full, arange, linspace, eye
Manipulation	               reshape, flatten, transpose, stacking & splitting
Math	                       sum, mean, min, max, std, argmax, cumsum
Logic	                       comparisons, any, all
Indexing	                  slicing, boolean mask, fancy indexing
Linear algebra	                inv, det, eig, solve, dot

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ndim
print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
#shape — tuple showing rows & columns
a.shape     # (2, 3)

(2, 3)

In [26]:
#size — total number of elements
a.size      # 6

6

In [27]:
#dtype — data type of elements
a.dtype    

dtype('int64')

In [ ]:
64-bit OS (most laptops/desktops) → int64

32-bit OS → int32
Type	Bytes per value
int32	4 bytes
int64	8 bytes

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#T — transpose (attribute)
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
#astype--- to convert the datatype
a.astype(np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

# array creation method

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((3,3), 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.empty((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Range-based

In [23]:
for i in range(1,10,2):          # in list
    print(i)

1
3
5
7
9


In [11]:
arr=np.arange(1, 10, 2)
print(arr)
arr*2

[1 3 5 7 9]


array([ 2,  6, 10, 14, 18])

In [13]:
np.linspace(1, 10, 9)  # with equal distance 

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [14]:
#Identity matrices

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Manipulation Methods

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#Reshaping
a.reshape(3, 4)

ValueError: cannot reshape array of size 6 into shape (3,4)

In [ ]:
Flattening

In [51]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
Transpose

In [54]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
a.transpose()

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [22]:
b=np.array([[[4,2],[6,4]],[[5,6],[17,8]]])
b[0]

array([[4, 2],
       [6, 4]])

In [18]:
b.T

array([[[ 4,  5],
        [ 6, 17]],

       [[ 2,  6],
        [ 4,  8]]])

# statistics


In [2]:
import numpy as np

In [30]:
data = np.array([10, 20, 30, 40, 50])
np.mean(data)

np.float64(30.0)

In [31]:
np.median(data)

np.float64(30.0)

In [ ]:
np.min(data)   # or data.min()
np.max(data)   # or data.max()

In [33]:
print(np.percentile(data, 75))  # 25th percentile  means 25% people is lagging behind you
np.percentile(data, 75)  # 75th percentile

40.0


np.float64(40.0)

In [ ]:
np.sum(data)   # 150
np.prod(data)  # 12000000

In [ ]:
np.arange(0,10,2) → Array from 0 to 8 with step 2
np.linspace(0,1,5) → 5 evenly spaced numbers between 0 and 1


# Broadcasting

In [ ]:
Broadcasting
Allows operations on arrays of different shapes.
NumPy automatically expands the smaller array along missing dimensions

In [ ]:
Array–Array Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

x + y        # [5, 7, 9]
x * y        # [4, 10, 18]
x-y
x>3
x*2

In [ ]:
Matrix Operations

In [71]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
#a.dot(b)
#A @ B               # matrix multiplication
np.dot(A, B)        # same


array([[19, 22],
       [43, 50]])

# Concatenation
# Joining arrays together.

In [75]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [73]:
# 1D concatenation
c = np.concatenate([a, b])
print(c)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [34]:
# 2D concatenation
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
# concatenate along rows (axis=0)
A =      B =
[1 2]   [5 6]
[3 4]   [7 8]

axis = 0
↓
[1 2]
[3 4]
[5 6]
[7 8]

In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
B

array([[5, 6],
       [7, 8]])

In [35]:
C = np.concatenate([A, B], axis=0)
print(C)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
 
# concatenate along columns (axis=1)
D = np.concatenate([A, B], axis=1)
print(D)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [81]:
arr1.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [1]:
import numpy as np

# indexing,slicing,iteration

In [2]:
a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [ ]:
a[0]     # 10
a[-1]    # 40

np.int64(40)

In [31]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A[0, 0]  # 1  (row 0, col 0)

np.int64(1)

In [5]:
A[1,2]  # 6  (row 1, col 2)

np.int64(6)

In [7]:
A[2,1] # 9  (last column)

np.int64(8)

In [9]:
a

array([10, 20, 30, 40])

In [10]:
# slicing 
A[1:3]   # [20, 30]

array([[4, 5, 6],
       [7, 8, 9]])

In [12]:
A[:3]  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[::2]   

array([20, 30])

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#A[r1:r2 , c1:c2]
A[1:2, 0:1]

array([[4]])

In [34]:
A[0:2, 0:1]   # row 0

array([[1],
       [4]])

In [ ]:
A[:, 1]   # column 1
A[1:, :]  # all rows except first
A[:,2]    #all row,2 col
A[:2]      #0,1 row
A[:,1:3]  #all row,1,2 col
A[2:4,1:3] # 4 SKIP,3 skip 

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A[0,2]

np.int64(3)

# Fancy Indexing



In [19]:
#Pick rows 0 and 2:
A[[0, 2]]
# [[1, 2, 3],
#  [7, 8, 9]]

array([[1, 2, 3],
       [7, 8, 9]])

In [37]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

# numpy function

In [ ]:
Random Number Functions (np.random)
Function	Purpose	Example
np.random.rand()	Uniform [0,1)	np.random.rand(3,2) Values are never negative
np.random.randn()	Standard normal	np.random.randn(3,2) Standard Normal distribution  Mean (μ) = 0,Standard deviation (σ) = 1
np.random.randint()	Random integers	np.random.randint(0,10,5)
np.random.choice()	Random selection	np.random.choice([1,2,3],3)
np.random.seed()	Fix random seed	np.random.seed(42)

In [118]:
np.random.rand(3,3)         #0-1

array([[0.5249915 , 0.75462513, 0.18097214],
       [0.88496502, 0.84360504, 0.16171687],
       [0.05780147, 0.68019652, 0.65430878]])

In [28]:
np.random.randn(3,2)   #Values can be negative or positiv ,There is no fixed range ❌,Most values fall between -3 and +3,-2 and +2

array([[-0.8380058 , -1.64889052],
       [-1.06569608,  0.48716436],
       [ 0.54967523, -1.59592301]])

In [42]:
np.random.randint(0,100,5)

array([10, 29, 87, 99, 88], dtype=int32)

In [44]:
np.random.choice([1,2,3,4,5,6],3)

array([1, 5, 5])

In [46]:

np.random.seed(42)
np.random.randint(0,100,5)

array([51, 92, 14, 71, 60], dtype=int32)


# sorted  return python list 


In [30]:
a = np.random.randint(1, 100, 15)
print(a)
np.sort(a)#Returns a sorted copy of a (does not modify a in-place).
#sorted_list = np.sort(a).tolist()

[10 74 69  3 53 94 11 38  3 97 82 76 13 93 85]


array([ 3,  3, 10, 11, 13, 38, 53, 69, 74, 76, 82, 85, 93, 94, 97],
      dtype=int32)

In [6]:
#L=[1,2,3,4,5,6]
d={'a':2,'b':3}
a=np.array(d)

In [40]:
a

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [7]:
np.array(list(d.items()))

array([['a', '2'],
       ['b', '3']], dtype='<U21')

# With Tuple

In [8]:


t = (1, 2, 3)
a = np.array(t)
print(a)

[1 2 3]


In [ ]:
# With Set

In [9]:
s = {1, 2, 3}
a = np.array(s)
print(a)

{1, 2, 3}


In [ ]:
#If using a set, convert to list
np.array(list(s))

In [23]:

b = np.array([[12, 55, 3],
              [78, 45, 7],
              [33, 90, 21]])
#Sort along axis=0 (i.e., column-wise)
np.sort(b, axis=0)
#Sorts each column independently.

array([[12, 45,  3],
       [33, 55,  7],
       [78, 90, 21]])

In [27]:
b

array([[12, 55,  3],
       [78, 45,  7],
       [33, 90, 21]])

In [30]:
a=np.array([[10,10],[20,20]])
np.sum(a,axis=0)

array([30, 30])

In [28]:
#Sort along axis=1 ( i.e., row-wise)
np.sum(b, axis=1)

array([ 70, 130, 144])

# THANKS